### ISSUE TITLE
bounty_escrow: duplicate enum discriminant 26 (ApprovalRequired vs UpgradeNotApproved) breaks the test build with E0081 — CI red on main since #582

### ISSUE THREAD

**Issue by XxHugheadxX** [Grainlify/Grainlify-Stellar-Contracts#598]
## Problem
`bounty_escrow/contracts/escrow/src/lib.rs` assigns discriminant `26` to two
variants of the contract error enum:

- `ApprovalRequired = 26` (line 419, added in #582)
- `UpgradeNotApproved = 26` (line 423, added earlier in #524)

Rust rejects this outright (`error[E0081]: discriminant value 26 assigned more
than once`), so the `bounty-escrow` lib test target no longer compiles. The
`Bounty Escrow - Build & Test` CI job has been failing on every run of `main`
since #582 landed (first red run: July 30), e.g.
https://github.com/Grainlify/Grainlify-Stellar-Contracts/actions/runs/30526668166
— which also means the entire bounty_escrow test suite (including the new
multisig enforcement tests from #582 themselves) hasn't actually run in CI
since then, and every open PR shows an inherited red check.

## Suggested fix
Renumber `ApprovalRequired` to the next free discriminant (`31` — 27 through
30 are taken). `UpgradeNotApproved` should keep `26`: it predates the
collision and the SDK's `BOUNTY_ESCROW_ERROR_MAP` already maps
`26 → BOUNTY_UPGRADE_NOT_APPROVED` (`sdk/src/errors.ts:244`), so this choice
avoids breaking the existing SDK mapping. Nothing references
`ApprovalRequired` by its numeric value (contract code and tests use
`Error::ApprovalRequired` by name), so the renumber is safe.

I'm opening a PR with the fix.

**Comment by Obiajulu-gif** [comment]
i will love to work on this issue

**Comment by Samaro1** [comment]
Gm gm boss. I would like to take this one on. I can renumber ApprovalRequired to the next free discriminant (31), leave UpgradeNotApproved at 26 to keep the SDK's error map intact, confirm nothing references ApprovalRequired by its numeric value, and get the bounty_escrow test target compiling and green in CI again. Please assign it to me.

**Comment by Jagadeeshftw** [comment]
## Assignment update — bounty escrow build repair

Good luck, @Obiajulu-gif — you are assigned to investigate the duplicate error discriminant in this bounty-escrow issue. Please read the complete issue description before coding, preserve the SDK mapping decisions it calls out, and make sure your PR addresses every requirement and verification item listed there. Please raise a high-quality PR with focused changes, clear tests, and useful evidence rather than only making the compiler error disappear.

Please open the PR within 48 hours of this assignment. If there is no PR by then, the issue may be unassigned so another contributor can take it. When you submit, include the appropriate issue-closing reference and join our Telegram group for coordination: https://t.me/+u5qmu35nZ7I0OTU1
